#!/usr/bin/env python

import sys
import os

import gitautoversion as gita

LOCKFILE = ".skip-post-commit-hook.lock"

if os.path.isfile(LOCKFILE):
   sys.exit(0)

print("git-auto-version[post-commit]: updating version tags and CHANGELOG.md")

# update change log
commits = gita.gitlog(last_hash=False)
gita.gittags(commits, update_commits=True)
changelog = gita.changelog(commits)
with open("CHANGELOG.md", "w") as f:
   f.write(changelog)

# update (ammend) the commit with the update change log
os.system("git add CHANGELOG.md")
open(LOCKFILE, "w").close()
os.system("git commit --amend --no-edit")
os.remove(LOCKFILE)

# set version tags
commits = gita.gitlog()
tags = gita.gittags(commits)
for (hsh, ver) in tags:
   tag = gita.gitversion(ver)
   cmd = f"git tag -a {tag} {hsh} -m 'Version {tag}'"
   print(f"git-auto-version[post-commit]: settting version tag {tag} for commit {hsh}")
   os.system(cmd)

