#!/usr/bin/env python

import sys
import os

import gittools

LOCKFILE = ".skip-post-commit-hook"
PUSHTAGS = ".push-tags-needed"

if os.path.isfile(LOCKFILE):
   sys.exit(0)

print("post-commit: Updating version tags and CHANGELOG.md")

commits = gittools.gitlog()

# set version tags

tags = gittools.gittags(commits)
if tags:
   for (hsh, ver) in tags:
      tag = gitversion(ver)
      cmd = f"git tag -a {tag} {hsh} -m 'Version {tag}'"
      print(cmd)
      os.system(cmd)
   print("new tags set")
   open(PUSHTAGS, "w").close()

# update change log

changelog = gittools.changelog(commits)
with open("CHANGELOG.md", "w") as f:
   f.write(changelog)

# update the commit with the latest changes

open(LOCKFILE, "w").close()
os.system("git add CHANGELOG.md")
os.system("git commit --amend --no-edit")
os.remove(LOCKFILE)

