#!/usr/bin/env python

import sys
import os

import gittools

print("post-commit: Updating version tags and CHANGELOG.md")

commits = gittools.gitlog()

# set version tags

# update change log

changelog = gittools.changelog(commits)
with open("CHANGELOG.md", "w") as f:
   f.write(changelog)

os.system("git add CHANGELOG.md")
os.system("git commit --amend --no-edit --no-verify")

