
@startuml
skinparam backgroundColor transparent

abstract class solverpy.solver.SolverPy {
  {abstract} # statuses : set[Status]
  --
  {abstract} + solve(instance, strategy) : Result
  + solved(result) : bool
}

class solverpy.solver.atp.eprover.E extends solverpy.solver.SolverPy
class solverpy.solver.atp.vampire.Vampire extends solverpy.solver.SolverPy
class solverpy.solver.atp.lash.Lash extends solverpy.solver.SolverPy
class solverpy.solver.atp.prover9.Prover9 extends solverpy.solver.SolverPy

class solverpy.solver.smt.cvc5.Cvc5 extends solverpy.solver.SolverPy
class solverpy.solver.smt.z3.Z3 extends solverpy.solver.SolverPy
class solverpy.solver.smt.bitwuzla.Bitwuzla extends solverpy.solver.SolverPy
@enduml
