
@startuml
skinparam backgroundColor transparent

class solverpy.report.talker.talker.Talker {
   - _log_queue: Queue[Any] | None
   - _listener: QueueListener | None

   --
   + {static} log_config(queue)
   + log_prepare()
   + log_start()
   + log_stop()
   + listening_start()
   + listening_stop()
   + begin(jobs, refjob, sidnames, **kwargs)
   + end(results, refjob)
   + next(job)
   + terminate()
   + launching(tasks)
   + finished(task, result)
   + done()
}
class solverpy.report.talker.logtalker.LogTalker extends solverpy.report.talker.talker.Talker
class solverpy.report.talker.remotetalker.RemoteTalker extends solverpy.report.talker.talker.Talker
@enduml
