#!/usr/bin/env python

def arguments():
   import argparse
   parser = argparse.ArgumentParser(description=
      "Process input and optional output file.")
   parser.add_argument("input", metavar="input.in", help="Path to input file")
   parser.add_argument("output", metavar="output.in", nargs='?', 
      default="deconflicted.in", help="Path to output file (default: deconflicted.in)")
   parser.add_argument("-v", "--verbose", action="store_true",
      help="Show more details.") 
   args = parser.parse_args()
   return args

def main(f_in, f_out):
   from solverpy.builder import svm
   (xs, ys) = svm.load(f_in)
   (xs0, ys0) = svm.deconflict(xs, ys)
   svm.save(xs0, ys0, f_out)

if __name__ == "__main__":
   import logging
   #logger = logging.getLogger(__name__)
   args = arguments()
   level = logging.DEBUG if args.verbose else logging.INFO
   logging.basicConfig(level=level, format="%(message)s")
   main(args.input, args.output)

